- name: Remove Git Project Directory (If Exist)
  become: true
  file:
    path: "{{ remote_path_for_repo }}"
    state: absent

- name: Clone Binance Scraper Project
  git:
    repo: "{{ repo_address }}"
    dest: "{{ remote_path_for_repo }}"
    single_branch: yes
    version: main

- name: Change Repo's DIR Files Owner
  command: "sudo chown {{ lookup('env', 'USER') }}:{{ lookup('env', 'USER') }} {{ remote_path_for_repo }}"
