---

- hosts: all
  gather_facts: yes
  become: true

  pre_tasks:
    - name: Initialize Runtime Variables
      include_role:
        name: init_runtime_variables

    - name: Install Updates (yum Package Manager)
      tags: always
      yum:
        update_only: true
        update_cache: yes
        state: latest
      when: server_package_manager == "yum"
    
    - name: Install Updates (apt Package Manager)
      tags: always
      apt:
        upgrade: yes
        update_cache: yes
        state: latest
      when: server_package_manager == "apt"

  roles:
    - clone_repo
    - init_enviroment

